# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x08grpc_gen\"K\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x18\n\x10\x61vailable_copies\x18\x04 \x01(\x05\"B\n\x11\x43reateBookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0e\n\x06\x63opies\x18\x03 \x01(\x05\")\n\x08\x42ookList\x12\x1d\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0e.grpc_gen.Book\"1\n\x06Member\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"2\n\x13\x43reateMemberRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"7\n\x11\x42orrowBookRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\x11\n\tmember_id\x18\x02 \x01(\x05\"!\n\x0e\x42orrowResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x11ReturnBookRequest\x12\x14\n\x0c\x62orrowing_id\x18\x01 \x01(\x05\"!\n\x0eReturnResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x08MemberId\x12\x11\n\tmember_id\x18\x01 \x01(\x05\"]\n\x0c\x42orrowedBook\x12\x14\n\x0c\x62orrowing_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x62orrow_date\x18\x03 \x01(\t\x12\x13\n\x0breturn_date\x18\x04 \x01(\t\"9\n\x10\x42orrowedBookList\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.grpc_gen.BorrowedBook\"\x07\n\x05\x45mpty2\x92\x03\n\x0eLibraryService\x12\x39\n\nCreateBook\x12\x1b.grpc_gen.CreateBookRequest\x1a\x0e.grpc_gen.Book\x12\x30\n\tListBooks\x12\x0f.grpc_gen.Empty\x1a\x12.grpc_gen.BookList\x12?\n\x0c\x43reateMember\x12\x1d.grpc_gen.CreateMemberRequest\x1a\x10.grpc_gen.Member\x12\x43\n\nBorrowBook\x12\x1b.grpc_gen.BorrowBookRequest\x1a\x18.grpc_gen.BorrowResponse\x12\x43\n\nReturnBook\x12\x1b.grpc_gen.ReturnBookRequest\x1a\x18.grpc_gen.ReturnResponse\x12H\n\x16ListBorrowBookByMember\x12\x12.grpc_gen.MemberId\x1a\x1a.grpc_gen.BorrowedBookListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=27
  _globals['_BOOK']._serialized_end=102
  _globals['_CREATEBOOKREQUEST']._serialized_start=104
  _globals['_CREATEBOOKREQUEST']._serialized_end=170
  _globals['_BOOKLIST']._serialized_start=172
  _globals['_BOOKLIST']._serialized_end=213
  _globals['_MEMBER']._serialized_start=215
  _globals['_MEMBER']._serialized_end=264
  _globals['_CREATEMEMBERREQUEST']._serialized_start=266
  _globals['_CREATEMEMBERREQUEST']._serialized_end=316
  _globals['_BORROWBOOKREQUEST']._serialized_start=318
  _globals['_BORROWBOOKREQUEST']._serialized_end=373
  _globals['_BORROWRESPONSE']._serialized_start=375
  _globals['_BORROWRESPONSE']._serialized_end=408
  _globals['_RETURNBOOKREQUEST']._serialized_start=410
  _globals['_RETURNBOOKREQUEST']._serialized_end=451
  _globals['_RETURNRESPONSE']._serialized_start=453
  _globals['_RETURNRESPONSE']._serialized_end=486
  _globals['_MEMBERID']._serialized_start=488
  _globals['_MEMBERID']._serialized_end=517
  _globals['_BORROWEDBOOK']._serialized_start=519
  _globals['_BORROWEDBOOK']._serialized_end=612
  _globals['_BORROWEDBOOKLIST']._serialized_start=614
  _globals['_BORROWEDBOOKLIST']._serialized_end=671
  _globals['_EMPTY']._serialized_start=673
  _globals['_EMPTY']._serialized_end=680
  _globals['_LIBRARYSERVICE']._serialized_start=683
  _globals['_LIBRARYSERVICE']._serialized_end=1085
# @@protoc_insertion_point(module_scope)
